[package]
name = "esp8266"
description = "The Arduino esp8266 core from Rust: time, serial, pins, i2c, wifi, udp and flash"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
esp8266-sys = { path = "../esp8266-sys" }

[lints]
workspace = true
