[package]
name = "hello"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
esp8266 = { path = "../../../esp8266" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

# unoptimized code runs llvm out of registers on this chip
[profile.dev]
opt-level = 1
panic = "abort"
